"""ZeroGraph constants."""

START = "__start__"
END = "__end__"
TAG_HIDDEN = "langsmith:hidden"

TASKS = "__tasks__"
INTERRUPT = "__interrupt__"
RESUME = "__resume__"
ERROR = "__error__"
ERROR_SOURCE_NODE = "__error_source_node__"
NO_WRITES = "__no_writes__"
PULL = "__pull__"
PUSH = "__push__"
RETURN = "__return__"
PREVIOUS = "__previous__"
OVERWRITE = "__overwrite__"
NS_SEP = "|"
NS_END = ":"
NULL_TASK_ID = ""
CONF = "__configurable__"

CONFIG_KEY_SEND = "__send__"
CONFIG_KEY_READ = "__read__"
CONFIG_KEY_TASK_ID = "__task_id__"
CONFIG_KEY_CHECKPOINTER = "__checkpointer__"
CONFIG_KEY_THREAD_ID = "__thread_id__"
CONFIG_KEY_CHECKPOINT_NS = "checkpoint_ns"
CONFIG_KEY_CHECKPOINT_ID = "__checkpoint_id__"
CONFIG_KEY_CHECKPOINT_MAP = "__checkpoint_map__"
CONFIG_KEY_RESUME_MAP = "__resume_map__"
CONFIG_KEY_SCRATCHPAD = "__scratchpad__"
CONFIG_KEY_RUNTIME = "__runtime__"
CONFIG_KEY_NODE_ERROR = "__node_error__"
CONFIG_KEY_WRITER = "__writer__"
CONFIG_KEY_STORE = "__store__"
CONFIG_KEY_CACHE = "__cache__"
CONFIG_KEY_CONTEXT = "__context__"

RESERVED = frozenset({NO_WRITES, PUSH, RESUME, INTERRUPT, RETURN, ERROR, ERROR_SOURCE_NODE})
